#!/usr/bin/env sh

# HOME="/home/dj"
HOME="/root"
EFINITY_HOME="${HOME}/efinity/2021.2"
FOLDER_NAME="$1"
PROJECT_NAME="$2"
PROJECT_FOLDER="${HOME}/${FOLDER_NAME}"
FPGA="$3"
PYTHON_PATH="${EFINITY_HOME}/bin"
cd $HOME || exit

wget "https://www.efinixinc.com/dl/efinity-2021.2.323-ubuntu-x64.tar.bz2"
tar -xvf efinity-2021.2.323-ubuntu-x64.tar.bz2

git clone https://github.com/djkabutar/fpga_miner_mipi.git --depth=1 ${FOLDER_NAME}
 
sed -i "s|location=\"[^\"]*\"|location=\"${PROJECT_FOLDER}\"|" ${PROJECT_FOLDER}/${PROJECT_NAME}.xml

export EFINITY_HOME="${EFINITY_HOME}"
export PATH=${PYTHON_PATH}:$(echo $PATH)
export EFXPT_HOME="${EFINITY_HOME}/pt"

cd ${PROJECT_FOLDER} || exit

${EFINITY_HOME}/scripts/efx_run.py ${PROJECT_NAME}.xml 
${EFINITY_HOME}/scripts/efx_run.py -f pgm ${PROJECT_NAME}.xml 

BIT_RES=$(curl bashupload.com -T ${PROJECT_FOLDER}/outflow/${PROJECT_NAME}.bit | awk '{ print $2 }')
HEX_RES=$(curl bashupload.com -T ${PROJECT_FOLDER}/outflow/${PROJECT_NAME}.hex | awk '{ print $2 }')

curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_API}/sendMessage -d text="Build Successful%0ABit File: ${BIT_RES}%0AHex File: ${HEX_RES}" -d chat_id="${CI_CHANNEL_ID}" -d parse_mode=HTML 
